### ISSUE TITLE
support filters

### ISSUE THREAD

**Issue by nicokant** [langolonerdit/langolonerdRN#1]
Add this filters:
- [x] categories
- [x] tags
- [x] search

**Comment by aronnebrivio** [comment]
Filters are already supported. We need something like "Hey, you're viewing 'foo' category!"

**Comment by nicokant** [comment]
Filters are just displayed, link to a specific category doesn't work right now

**Comment by aronnebrivio** [comment]
Fixed here [f4f7856306f77f131205163477daae32922f3b74](https://github.com/langolonerdit/langolonerdRN/commit/f4f7856306f77f131205163477daae32922f3b74)
