### ISSUE TITLE
Warning: you are manually calling a React.PropTypes validation function

### ISSUE THREAD

**Issue by nicokant** [langolonerdit/langolonerdRN#8]
... for the 'paddingLeft' prop on '<<anonymous>>'. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third party PropTypes library. see https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by aronnebrivio** [comment]
It's something related a deprecated validation function in [fence-html-react-native library](https://github.com/Thomas101/react-native-fence-html). I think it will be a `wontfix` bug

**Comment by nicokant** [comment]
Yeah.. this bug was already issued with a relative PR on 16 November 2016, but there are still no responses. https://github.com/Thomas101/react-native-fence-html/issues/13

**Comment by nicokant** [comment]
In this comment of react-native-html-view a guy says:
> import HTML from 'react-native-fence-html'; Works only text the best so far
> import HTML from 'react-native-html-converter'; No sucess even with text
> import HTML from 'react-native-htmlview'; Works only text
> import HTML from 'react-native-webview'; No sucess
> import HTML from 'react-native-webview-android; No sucess

https://github.com/jsdf/react-native-htmlview/issues/57#issuecomment-287511549

**Comment by aronnebrivio** [comment]
Until Thomas101 will fix it in the library

**Comment by aronnebrivio** [comment]
I think we should check this PR [https://github.com/Thomas101/react-native-fence-html/pull/15](https://github.com/Thomas101/react-native-fence-html/pull/15)

**Comment by nicokant** [comment]
Reopened the issue waiting for fix in https://github.com/langolonerdit/fence-html-rn

**Comment by aronnebrivio** [comment]
Fixed here: [https://github.com/langolonerdit/fence-html-rn/commit/54d09c2edb704077f47d550eecab4e027ec7f73c](https://github.com/langolonerdit/fence-html-rn/commit/54d09c2edb704077f47d550eecab4e027ec7f73c)
